spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.34.65.69:3306/h2o
    username: h2o
    password: 1